export const SET_TOKEN = 'SET_TOKEN'
export const SET_USER = 'SET_USER'
export const SET_USER_KEY = 'SET_USER_KEY'
export const SET_USER_ADDRESS = 'SET_USER_ADDRESS'
export const SET_USER_ADDRESSES = 'SET_USER_ADDRESSES'
export const ADD_ADDRESS = 'ADD_ADDRESS'
export const ADD_CARD = 'ADD_CARD'
export const SET_USER_AVATAR = 'SET_USER_AVATAR'

export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_SUB_CATEGORIES = 'SET_SUB_CATEGORIES'
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY'
export const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST'

export const SET_BLOGS = 'SET_BLOGS'

export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_PRODUCT = 'SET_PRODUCT'

export const SET_SERVICES = 'SET_SERVICES'
export const SET_SERVICE_CATEGORY = 'SET_SERVICE_CATEGORY'

export const TOGGLE_SIDE_MENU = 'TOGGLE_SIDE_MENU'
export const TOGGLE_LEFT_MENU = 'TOGGLE_LEFT_MENU'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const UPDATE_MODAL = 'UPDATE_MODAL'
export const SHOW_ALERT = 'SHOW_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const TOGGLE_LIGHT_BOX = 'TOGGLE_LIGHT_BOX'

export const SET_LOCATION = 'SET_LOCATION'

export const SET_CART = 'SET_CART'
export const SET_CART_TOTAL = 'SET_CART_TOTAL'
export const SET_STEP = 'SET_STEP'
export const SET_GUEST_INFO = 'SET_GUEST_INFO'

export const SET_SCHEDULE_CART = 'SET_SCHEDULE_CART'
export const SET_SCHEDULE_STEP = 'SET_SCHEDULE_STEP'
export const SET_GUEST_CARD = 'SET_GUEST_CARD'

export const SET_SEARCH = 'SET_SEARCH'
export const SET_FILTERS = 'SET_FILTERS'
export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE'