export const SET_TOKEN = 'SET_TOKEN'
export const SET_USER = 'SET_USER'

export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY'

export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_PRODUCT = 'SET_PRODUCT'

export const SET_SERVICES = 'SET_SERVICES'
export const SET_SERVICE_CATEGORY = 'SET_SERVICE_CATEGORY'

export const TOGGLE_SIDE_MENU = 'TOGGLE_SIDE_MENU'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'